project:
  type: website
  output-dir: docs

website:
  title: "Dinara Zhorabek"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: Intro
        href: index.qmd#intro
      - text: Portfolio
        href: index.qmd#projects

format:
  html:
    theme:
      - minty
      - brand
    css: styles.css
    toc: true
    code-fold: true

execute: 
  warning: false



