project:
  type: website
  # output-dir: docs

website:
  title: "Dinara Zhorabek"
  navbar: false
    # left:
    #   - href: index.qmd
    #     text: Home
    #   - text: Intro
    #     href: index.qmd#intro
    #   - text: Portfolio
    #     href: index.qmd#projects

format:
  html:
    css: styles.css
    toc: true
    toc-location: right
    toc-depth: 4
    page-layout: full
    include-before-body: includes/gh-start.html
    include-after-body: includes/gh-end.html
    code-fold: true

  html-home:
    css: styles.css
    toc: false
    page-layout: full
    code-fold: true


execute: 
  warning: false



